spring:
  cloud:
    gateway:
      routes:
        # 1. NEW ROUTE for the Customer Identity Service
        - id: customer-identity-route
          uri: lb://CUSTOMER-IDENTITY-SERVICE # Use the service ID from Eureka
          predicates:
            - Path=/api/v1/users/**

        # 2. We will add routes here later, e.g., to the customer-service
        - id: placeholder-route
          uri: https://httpbin.org/get # A placeholder to test
          predicates:
            - Path=/test/**

# This tells the gateway how to find the Eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 🔑 ADD THIS BLOCK 🔑
spring:
  cloud:
    loadbalancer:
      # This forces the Load Balancer to use the resolved IP (127.0.0.1) as the 
      # destination hostname, which is required for local loopback routing to work.
      use-legacy-processing: true