# This configuration is retrieved by the service from the Config Server


# --- Database Configuration (MySQL) ---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_identity_db # CHANGE: Use your actual MySQL IP/Host
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Good for dev, change to 'none' or 'validate' for prod
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# --- Eureka Client Configuration ---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # The address of the Eureka Server
  instance:
    # Use the application name as the service ID in Eureka
    instance-id: ${spring.application.name}:${random.value}